#
# Copyright (C) 2024 The Android Open Source Project
# Copyright (C) 2024 The TWRP Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

# For building with minimal manifest
export ALLOW_MISSING_DEPENDENCIES=true
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export FOX_VANILLA_BUILD=1
export OF_SCREEN_H="2400"
export OF_HIDE_NOTCH=1
export OF_CLOCK_POS=1
export OF_ALLOW_DISABLE_NAVBAR=0
export FOX_TARGET_DEVICES="z3s, z3sxxx"
export OF_USE_SYSTEM_FINGERPRINT=1
export OF_USE_TWRP_SAR_DETECT=1
export OF_STATUS_INDENT_LEFT="64"
export OF_STATUS_INDENT_RIGHT="64"
export OF_STATUS_H="88"
export OF_USE_GREEN_LED=0
export OF_SUPPORT_PRE_FLASH_SCRIPT=1
export OF_DEFAULT_KEYMASTER_VERSION=4.0
export FOX_DYNAMIC_SAMSUNG_FIX=1
export FOX_REMOVE_AAPT=1
export FOX_DELETE_MAGISK_ADDON=1
export OF_USE_MAGISKBOOT=0
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=0
export OF_FL_PATH1="/tmp/flashlight"
export OF_FL_PATH2=""
export OF_FLASHLIGHT_ENABLE=1
export OF_RUN_POST_FORMAT_PROCESS=1
